/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Academics: () => import('#controllers/academics_controller'),
  Admin: () => import('#controllers/admin_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Dashboard: () => import('#controllers/dashboard_controller'),
  Disciplines: () => import('#controllers/disciplines_controller'),
  Financials: () => import('#controllers/financials_controller'),
  Help: () => import('#controllers/help_controller'),
  Inspections: () => import('#controllers/inspections_controller'),
  InterSchools: () => import('#controllers/inter_schools_controller'),
  Messages: () => import('#controllers/messages_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Parents: () => import('#controllers/parents_controller'),
  Pedagogicals: () => import('#controllers/pedagogicals_controller'),
  Schools: () => import('#controllers/schools_controller'),
  Session: () => import('#controllers/session_controller'),
  Students: () => import('#controllers/students_controller'),
  Teachers: () => import('#controllers/teachers_controller'),
  Transfers: () => import('#controllers/transfers_controller'),
  Welcome: () => import('#controllers/welcome_controller'),
}
