/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AssignmentSubmissionSchema extends BaseModel {
  static $columns = ['assignmentId', 'attachmentUrl', 'createdAt', 'grade', 'id', 'isLate', 'status', 'studentId', 'submissionContent', 'submittedAt', 'teacherFeedback', 'updatedAt'] as const
  $columns = AssignmentSubmissionSchema.$columns
  @column()
  declare assignmentId: string | null
  @column()
  declare attachmentUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare grade: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isLate: boolean | null
  @column()
  declare status: string | null
  @column()
  declare studentId: string | null
  @column()
  declare submissionContent: string | null
  @column.dateTime()
  declare submittedAt: DateTime | null
  @column()
  declare teacherFeedback: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AssignmentSchema extends BaseModel {
  static $columns = ['attachmentUrl', 'classId', 'createdAt', 'description', 'dueDate', 'dueTime', 'id', 'instructions', 'maxPoints', 'publishedAt', 'status', 'subjectId', 'teacherId', 'title', 'updatedAt'] as const
  $columns = AssignmentSchema.$columns
  @column()
  declare attachmentUrl: string | null
  @column()
  declare classId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column.date()
  declare dueDate: DateTime
  @column()
  declare dueTime: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare instructions: string | null
  @column()
  declare maxPoints: number | null
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column()
  declare status: string | null
  @column()
  declare subjectId: string | null
  @column()
  declare teacherId: string | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AttendanceSchema extends BaseModel {
  static $columns = ['classId', 'createdAt', 'date', 'id', 'justification', 'justificationDocument', 'justifiedAt', 'justifiedBy', 'period', 'reason', 'recordedBy', 'status', 'studentId', 'updatedAt'] as const
  $columns = AttendanceSchema.$columns
  @column()
  declare classId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.date()
  declare date: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare justification: string | null
  @column()
  declare justificationDocument: string | null
  @column.dateTime()
  declare justifiedAt: DateTime | null
  @column()
  declare justifiedBy: string | null
  @column()
  declare period: string
  @column()
  declare reason: string | null
  @column()
  declare recordedBy: string | null
  @column()
  declare status: string
  @column()
  declare studentId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ClassSubjectSchema extends BaseModel {
  static $columns = ['classId', 'createdAt', 'hoursPerWeek', 'id', 'subjectId', 'teacherId', 'updatedAt'] as const
  $columns = ClassSubjectSchema.$columns
  @column()
  declare classId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare hoursPerWeek: number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare subjectId: string | null
  @column()
  declare teacherId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ClassSchema extends BaseModel {
  static $columns = ['academicYear', 'createdAt', 'currentEnrollment', 'gradeLevel', 'id', 'level', 'maxCapacity', 'name', 'schoolId', 'shift', 'teacherId', 'updatedAt'] as const
  $columns = ClassSchema.$columns
  @column()
  declare academicYear: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare currentEnrollment: number | null
  @column()
  declare gradeLevel: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare level: string
  @column()
  declare maxCapacity: number | null
  @column()
  declare name: string
  @column()
  declare schoolId: string | null
  @column()
  declare shift: string | null
  @column()
  declare teacherId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DisciplineSchema extends BaseModel {
  static $columns = ['actionTaken', 'createdAt', 'description', 'id', 'incidentDate', 'incidentType', 'parentNotified', 'parentNotifiedAt', 'parentResponse', 'reportedBy', 'sanction', 'severity', 'studentId', 'updatedAt'] as const
  $columns = DisciplineSchema.$columns
  @column()
  declare actionTaken: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: string
  @column.date()
  declare incidentDate: DateTime
  @column()
  declare incidentType: string | null
  @column()
  declare parentNotified: boolean | null
  @column.dateTime()
  declare parentNotifiedAt: DateTime | null
  @column()
  declare parentResponse: string | null
  @column()
  declare reportedBy: string | null
  @column()
  declare sanction: string | null
  @column()
  declare severity: string | null
  @column()
  declare studentId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class FeePaymentSchema extends BaseModel {
  static $columns = ['amountPaid', 'createdAt', 'currency', 'feeId', 'id', 'notes', 'paymentDate', 'paymentMethod', 'receiptNumber', 'recordedBy', 'referenceNumber', 'studentId', 'updatedAt'] as const
  $columns = FeePaymentSchema.$columns
  @column()
  declare amountPaid: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare currency: string | null
  @column()
  declare feeId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare notes: string | null
  @column.date()
  declare paymentDate: DateTime
  @column()
  declare paymentMethod: string | null
  @column()
  declare receiptNumber: string | null
  @column()
  declare recordedBy: string | null
  @column()
  declare referenceNumber: string | null
  @column()
  declare studentId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ForumPostSchema extends BaseModel {
  static $columns = ['content', 'createdAt', 'id', 'isApproved', 'parentPostId', 'topicId', 'updatedAt', 'userId'] as const
  $columns = ForumPostSchema.$columns
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isApproved: boolean | null
  @column()
  declare parentPostId: string | null
  @column()
  declare topicId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string | null
}

export class ForumTopicSchema extends BaseModel {
  static $columns = ['classId', 'content', 'createdAt', 'createdBy', 'id', 'isLocked', 'isPinned', 'subjectId', 'title', 'updatedAt', 'viewsCount'] as const
  $columns = ForumTopicSchema.$columns
  @column()
  declare classId: string | null
  @column()
  declare content: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare createdBy: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isLocked: boolean | null
  @column()
  declare isPinned: boolean | null
  @column()
  declare subjectId: string | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare viewsCount: number | null
}

export class GradeSchema extends BaseModel {
  static $columns = ['classId', 'createdAt', 'examDate', 'examType', 'id', 'maxScore', 'percentage', 'published', 'publishedAt', 'score', 'studentId', 'subjectId', 'teacherComments', 'term', 'updatedAt'] as const
  $columns = GradeSchema.$columns
  @column()
  declare classId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.date()
  declare examDate: DateTime | null
  @column()
  declare examType: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare maxScore: number | null
  @column()
  declare percentage: number | null
  @column()
  declare published: boolean | null
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column()
  declare score: number | null
  @column()
  declare studentId: string | null
  @column()
  declare subjectId: string | null
  @column()
  declare teacherComments: string | null
  @column()
  declare term: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class InspectionSettingSchema extends BaseModel {
  static $columns = ['createdAt', 'group', 'key', 'updatedAt', 'value'] as const
  $columns = InspectionSettingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare group: string
  @column({ isPrimary: true })
  declare key: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare value: string | null
}

export class MessageSchema extends BaseModel {
  static $columns = ['content', 'createdAt', 'hasAttachment', 'id', 'isGlobal', 'isRead', 'readAt', 'receiverId', 'schoolId', 'senderId', 'subject', 'type', 'updatedAt'] as const
  $columns = MessageSchema.$columns
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare hasAttachment: boolean | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isGlobal: boolean | null
  @column()
  declare isRead: boolean | null
  @column.dateTime()
  declare readAt: DateTime | null
  @column()
  declare receiverId: string | null
  @column()
  declare schoolId: string | null
  @column()
  declare senderId: string | null
  @column()
  declare subject: string
  @column()
  declare type: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OtpCodeSchema extends BaseModel {
  static $columns = ['attempts', 'codeHash', 'createdAt', 'email', 'expiresAt', 'id', 'purpose', 'updatedAt', 'usedAt', 'userId'] as const
  $columns = OtpCodeSchema.$columns
  @column()
  declare attempts: number
  @column()
  declare codeHash: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare purpose: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare usedAt: DateTime | null
  @column()
  declare userId: string
}

export class ParentStudentSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isPrimary', 'parentId', 'studentId', 'updatedAt'] as const
  $columns = ParentStudentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isPrimary: boolean | null
  @column()
  declare parentId: string | null
  @column()
  declare studentId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ParentSchema extends BaseModel {
  static $columns = ['createdAt', 'emergencyPhone', 'id', 'profession', 'relationship', 'updatedAt', 'userId'] as const
  $columns = ParentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare emergencyPhone: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare profession: string | null
  @column()
  declare relationship: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string | null
}

export class RoleSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'name', 'permissions', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare permissions: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SchoolFeeSchema extends BaseModel {
  static $columns = ['academicYear', 'amount', 'createdAt', 'currency', 'description', 'feeType', 'id', 'isMandatory', 'schoolId', 'term', 'updatedAt'] as const
  $columns = SchoolFeeSchema.$columns
  @column()
  declare academicYear: string
  @column()
  declare amount: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare currency: string | null
  @column()
  declare description: string | null
  @column()
  declare feeType: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isMandatory: boolean | null
  @column()
  declare schoolId: string | null
  @column()
  declare term: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SchoolInspectionSchema extends BaseModel {
  static $columns = ['createdAt', 'followUpDate', 'id', 'inspectionDate', 'inspector', 'rating', 'recommendations', 'report', 'schoolId', 'updatedAt'] as const
  $columns = SchoolInspectionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.date()
  declare followUpDate: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column.date()
  declare inspectionDate: DateTime
  @column()
  declare inspector: string
  @column()
  declare rating: number | null
  @column()
  declare recommendations: string | null
  @column()
  declare report: string
  @column()
  declare schoolId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SchoolSchema extends BaseModel {
  static $columns = ['address', 'approvedAt', 'code', 'createdAt', 'email', 'hasElectricity', 'hasInternet', 'hasLibrary', 'id', 'logoUrl', 'name', 'phone', 'province', 'status', 'teacherId', 'territory', 'updatedAt'] as const
  $columns = SchoolSchema.$columns
  @column()
  declare address: string
  @column.dateTime()
  declare approvedAt: DateTime | null
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string | null
  @column()
  declare hasElectricity: boolean
  @column()
  declare hasInternet: boolean
  @column()
  declare hasLibrary: boolean
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare logoUrl: string | null
  @column()
  declare name: string
  @column()
  declare phone: string | null
  @column()
  declare province: string
  @column()
  declare status: string | null
  @column()
  declare teacherId: string | null
  @column()
  declare territory: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class StudentSchema extends BaseModel {
  static $columns = ['academicStatus', 'address', 'birthDate', 'birthPlace', 'classId', 'createdAt', 'gender', 'id', 'medicalInfo', 'nationality', 'parentPhone', 'registrationNumber', 'schoolId', 'schoolOption', 'shift', 'updatedAt', 'userId'] as const
  $columns = StudentSchema.$columns
  @column()
  declare academicStatus: string | null
  @column()
  declare address: string | null
  @column.date()
  declare birthDate: DateTime | null
  @column()
  declare birthPlace: string | null
  @column()
  declare classId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare gender: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare medicalInfo: string | null
  @column()
  declare nationality: string | null
  @column()
  declare parentPhone: string | null
  @column()
  declare registrationNumber: string
  @column()
  declare schoolId: string | null
  @column()
  declare schoolOption: string | null
  @column()
  declare shift: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string | null
}

export class SubjectSchema extends BaseModel {
  static $columns = ['code', 'coefficient', 'createdAt', 'description', 'id', 'name', 'updatedAt'] as const
  $columns = SubjectSchema.$columns
  @column()
  declare code: string
  @column()
  declare coefficient: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TeacherSchema extends BaseModel {
  static $columns = ['createdAt', 'employeeNumber', 'hireDate', 'id', 'qualification', 'schoolId', 'specialization', 'status', 'updatedAt', 'userId'] as const
  $columns = TeacherSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare employeeNumber: string
  @column.date()
  declare hireDate: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare qualification: string | null
  @column()
  declare schoolId: string | null
  @column()
  declare specialization: string | null
  @column()
  declare status: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string | null
}

export class TimetableSchema extends BaseModel {
  static $columns = ['academicYear', 'classId', 'createdAt', 'dayOfWeek', 'endTime', 'id', 'room', 'shift', 'startTime', 'subjectId', 'teacherId', 'term', 'updatedAt'] as const
  $columns = TimetableSchema.$columns
  @column()
  declare academicYear: string
  @column()
  declare classId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare dayOfWeek: number
  @column()
  declare endTime: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare room: string | null
  @column()
  declare shift: string | null
  @column()
  declare startTime: string
  @column()
  declare subjectId: string | null
  @column()
  declare teacherId: string | null
  @column()
  declare term: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TransferAuthorizationSchema extends BaseModel {
  static $columns = ['approvedBy', 'authorizationCode', 'createdAt', 'fromSchoolId', 'id', 'issuedAt', 'reason', 'rejectionReason', 'status', 'studentId', 'toSchoolId', 'updatedAt', 'validUntil'] as const
  $columns = TransferAuthorizationSchema.$columns
  @column()
  declare approvedBy: string | null
  @column()
  declare authorizationCode: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare fromSchoolId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare issuedAt: DateTime | null
  @column()
  declare reason: string | null
  @column()
  declare rejectionReason: string | null
  @column()
  declare status: string | null
  @column()
  declare studentId: string | null
  @column()
  declare toSchoolId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare validUntil: DateTime | null
}

export class UserSettingSchema extends BaseModel {
  static $columns = ['createdAt', 'group', 'id', 'key', 'updatedAt', 'userId', 'value'] as const
  $columns = UserSettingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare group: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare key: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
  @column()
  declare value: string | null
}

export class UserSchema extends BaseModel {
  static $columns = ['avatarUrl', 'createdAt', 'email', 'firstName', 'id', 'lastLogin', 'lastName', 'password', 'phone', 'postnom', 'preferredLanguage', 'rememberMeToken', 'role', 'schoolId', 'status', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatarUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column()
  declare firstName: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastLogin: DateTime | null
  @column()
  declare lastName: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare phone: string | null
  @column()
  declare postnom: string
  @column()
  declare preferredLanguage: string
  @column()
  declare rememberMeToken: string | null
  @column()
  declare role: string
  @column()
  declare schoolId: string | null
  @column()
  declare status: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
