/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'welcome.index': {
    methods: ["GET","HEAD"],
    pattern: '/',
    tokens: [{"old":"/","type":0,"val":"/","end":""}],
    types: placeholder as Registry['welcome.index']['types'],
  },
  'about': {
    methods: ["GET","HEAD"],
    pattern: '/about',
    tokens: [{"old":"/about","type":0,"val":"about","end":""}],
    types: placeholder as Registry['about']['types'],
  },
  'welcome.landing': {
    methods: ["GET","HEAD"],
    pattern: '/welcome',
    tokens: [{"old":"/welcome","type":0,"val":"welcome","end":""}],
    types: placeholder as Registry['welcome.landing']['types'],
  },
  'welcome.about': {
    methods: ["GET","HEAD"],
    pattern: '/welcome/about',
    tokens: [{"old":"/welcome/about","type":0,"val":"welcome","end":""},{"old":"/welcome/about","type":0,"val":"about","end":""}],
    types: placeholder as Registry['welcome.about']['types'],
  },
  'welcome.features': {
    methods: ["GET","HEAD"],
    pattern: '/welcome/features',
    tokens: [{"old":"/welcome/features","type":0,"val":"welcome","end":""},{"old":"/welcome/features","type":0,"val":"features","end":""}],
    types: placeholder as Registry['welcome.features']['types'],
  },
  'welcome.contact': {
    methods: ["GET","HEAD"],
    pattern: '/welcome/contact',
    tokens: [{"old":"/welcome/contact","type":0,"val":"welcome","end":""},{"old":"/welcome/contact","type":0,"val":"contact","end":""}],
    types: placeholder as Registry['welcome.contact']['types'],
  },
  'welcome.terms': {
    methods: ["GET","HEAD"],
    pattern: '/welcome/terms',
    tokens: [{"old":"/welcome/terms","type":0,"val":"welcome","end":""},{"old":"/welcome/terms","type":0,"val":"terms","end":""}],
    types: placeholder as Registry['welcome.terms']['types'],
  },
  'help.index': {
    methods: ["GET","HEAD"],
    pattern: '/help',
    tokens: [{"old":"/help","type":0,"val":"help","end":""}],
    types: placeholder as Registry['help.index']['types'],
  },
  'help.faq': {
    methods: ["GET","HEAD"],
    pattern: '/help/faq',
    tokens: [{"old":"/help/faq","type":0,"val":"help","end":""},{"old":"/help/faq","type":0,"val":"faq","end":""}],
    types: placeholder as Registry['help.faq']['types'],
  },
  'help.guides': {
    methods: ["GET","HEAD"],
    pattern: '/help/guides',
    tokens: [{"old":"/help/guides","type":0,"val":"help","end":""},{"old":"/help/guides","type":0,"val":"guides","end":""}],
    types: placeholder as Registry['help.guides']['types'],
  },
  'help.tutorial': {
    methods: ["GET","HEAD"],
    pattern: '/help/tutorial',
    tokens: [{"old":"/help/tutorial","type":0,"val":"help","end":""},{"old":"/help/tutorial","type":0,"val":"tutorial","end":""}],
    types: placeholder as Registry['help.tutorial']['types'],
  },
  'help.contact': {
    methods: ["GET","HEAD"],
    pattern: '/help/contact',
    tokens: [{"old":"/help/contact","type":0,"val":"help","end":""},{"old":"/help/contact","type":0,"val":"contact","end":""}],
    types: placeholder as Registry['help.contact']['types'],
  },
  'help.documentation': {
    methods: ["GET","HEAD"],
    pattern: '/help/documentation',
    tokens: [{"old":"/help/documentation","type":0,"val":"help","end":""},{"old":"/help/documentation","type":0,"val":"documentation","end":""}],
    types: placeholder as Registry['help.documentation']['types'],
  },
  'schools.register_school': {
    methods: ["POST"],
    pattern: '/api/v1/register-school',
    tokens: [{"old":"/api/v1/register-school","type":0,"val":"api","end":""},{"old":"/api/v1/register-school","type":0,"val":"v1","end":""},{"old":"/api/v1/register-school","type":0,"val":"register-school","end":""}],
    types: placeholder as Registry['schools.register_school']['types'],
  },
  'auth.login': {
    methods: ["POST"],
    pattern: '/api/v1/login',
    tokens: [{"old":"/api/v1/login","type":0,"val":"api","end":""},{"old":"/api/v1/login","type":0,"val":"v1","end":""},{"old":"/api/v1/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['auth.login']['types'],
  },
  'auth.forgot_password': {
    methods: ["POST"],
    pattern: '/api/v1/forgot-password',
    tokens: [{"old":"/api/v1/forgot-password","type":0,"val":"api","end":""},{"old":"/api/v1/forgot-password","type":0,"val":"v1","end":""},{"old":"/api/v1/forgot-password","type":0,"val":"forgot-password","end":""}],
    types: placeholder as Registry['auth.forgot_password']['types'],
  },
  'auth.reset_password': {
    methods: ["POST"],
    pattern: '/api/v1/reset-password',
    tokens: [{"old":"/api/v1/reset-password","type":0,"val":"api","end":""},{"old":"/api/v1/reset-password","type":0,"val":"v1","end":""},{"old":"/api/v1/reset-password","type":0,"val":"reset-password","end":""}],
    types: placeholder as Registry['auth.reset_password']['types'],
  },
  'transfers.verify_authorization': {
    methods: ["POST"],
    pattern: '/api/v1/verify-transfer',
    tokens: [{"old":"/api/v1/verify-transfer","type":0,"val":"api","end":""},{"old":"/api/v1/verify-transfer","type":0,"val":"v1","end":""},{"old":"/api/v1/verify-transfer","type":0,"val":"verify-transfer","end":""}],
    types: placeholder as Registry['transfers.verify_authorization']['types'],
  },
  'auth.logout': {
    methods: ["POST"],
    pattern: '/api/v1/logout',
    tokens: [{"old":"/api/v1/logout","type":0,"val":"api","end":""},{"old":"/api/v1/logout","type":0,"val":"v1","end":""},{"old":"/api/v1/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['auth.logout']['types'],
  },
  'auth.change_password': {
    methods: ["POST"],
    pattern: '/api/v1/change-password',
    tokens: [{"old":"/api/v1/change-password","type":0,"val":"api","end":""},{"old":"/api/v1/change-password","type":0,"val":"v1","end":""},{"old":"/api/v1/change-password","type":0,"val":"change-password","end":""}],
    types: placeholder as Registry['auth.change_password']['types'],
  },
  'auth.get_profile': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/profile',
    tokens: [{"old":"/api/v1/profile","type":0,"val":"api","end":""},{"old":"/api/v1/profile","type":0,"val":"v1","end":""},{"old":"/api/v1/profile","type":0,"val":"profile","end":""}],
    types: placeholder as Registry['auth.get_profile']['types'],
  },
  'auth.update_profile': {
    methods: ["PUT"],
    pattern: '/api/v1/profile',
    tokens: [{"old":"/api/v1/profile","type":0,"val":"api","end":""},{"old":"/api/v1/profile","type":0,"val":"v1","end":""},{"old":"/api/v1/profile","type":0,"val":"profile","end":""}],
    types: placeholder as Registry['auth.update_profile']['types'],
  },
  'inspections.get_all_schools': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/inspection/schools',
    tokens: [{"old":"/api/v1/inspection/schools","type":0,"val":"api","end":""},{"old":"/api/v1/inspection/schools","type":0,"val":"v1","end":""},{"old":"/api/v1/inspection/schools","type":0,"val":"inspection","end":""},{"old":"/api/v1/inspection/schools","type":0,"val":"schools","end":""}],
    types: placeholder as Registry['inspections.get_all_schools']['types'],
  },
  'inspections.get_school_by_id': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/inspection/schools/:id',
    tokens: [{"old":"/api/v1/inspection/schools/:id","type":0,"val":"api","end":""},{"old":"/api/v1/inspection/schools/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/inspection/schools/:id","type":0,"val":"inspection","end":""},{"old":"/api/v1/inspection/schools/:id","type":0,"val":"schools","end":""},{"old":"/api/v1/inspection/schools/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['inspections.get_school_by_id']['types'],
  },
  'inspections.approve_school': {
    methods: ["POST"],
    pattern: '/api/v1/inspection/schools/approve/:id',
    tokens: [{"old":"/api/v1/inspection/schools/approve/:id","type":0,"val":"api","end":""},{"old":"/api/v1/inspection/schools/approve/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/inspection/schools/approve/:id","type":0,"val":"inspection","end":""},{"old":"/api/v1/inspection/schools/approve/:id","type":0,"val":"schools","end":""},{"old":"/api/v1/inspection/schools/approve/:id","type":0,"val":"approve","end":""},{"old":"/api/v1/inspection/schools/approve/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['inspections.approve_school']['types'],
  },
  'inspections.suspend_school': {
    methods: ["POST"],
    pattern: '/api/v1/inspection/schools/suspend/:id',
    tokens: [{"old":"/api/v1/inspection/schools/suspend/:id","type":0,"val":"api","end":""},{"old":"/api/v1/inspection/schools/suspend/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/inspection/schools/suspend/:id","type":0,"val":"inspection","end":""},{"old":"/api/v1/inspection/schools/suspend/:id","type":0,"val":"schools","end":""},{"old":"/api/v1/inspection/schools/suspend/:id","type":0,"val":"suspend","end":""},{"old":"/api/v1/inspection/schools/suspend/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['inspections.suspend_school']['types'],
  },
  'inspections.inspect_school': {
    methods: ["POST"],
    pattern: '/api/v1/inspection/schools/inspect',
    tokens: [{"old":"/api/v1/inspection/schools/inspect","type":0,"val":"api","end":""},{"old":"/api/v1/inspection/schools/inspect","type":0,"val":"v1","end":""},{"old":"/api/v1/inspection/schools/inspect","type":0,"val":"inspection","end":""},{"old":"/api/v1/inspection/schools/inspect","type":0,"val":"schools","end":""},{"old":"/api/v1/inspection/schools/inspect","type":0,"val":"inspect","end":""}],
    types: placeholder as Registry['inspections.inspect_school']['types'],
  },
  'auth.generate_school_credentials': {
    methods: ["POST"],
    pattern: '/api/v1/inspection/schools/generate-credentials/:id',
    tokens: [{"old":"/api/v1/inspection/schools/generate-credentials/:id","type":0,"val":"api","end":""},{"old":"/api/v1/inspection/schools/generate-credentials/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/inspection/schools/generate-credentials/:id","type":0,"val":"inspection","end":""},{"old":"/api/v1/inspection/schools/generate-credentials/:id","type":0,"val":"schools","end":""},{"old":"/api/v1/inspection/schools/generate-credentials/:id","type":0,"val":"generate-credentials","end":""},{"old":"/api/v1/inspection/schools/generate-credentials/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['auth.generate_school_credentials']['types'],
  },
  'inspections.send_global_communication': {
    methods: ["POST"],
    pattern: '/api/v1/inspection/communications/global',
    tokens: [{"old":"/api/v1/inspection/communications/global","type":0,"val":"api","end":""},{"old":"/api/v1/inspection/communications/global","type":0,"val":"v1","end":""},{"old":"/api/v1/inspection/communications/global","type":0,"val":"inspection","end":""},{"old":"/api/v1/inspection/communications/global","type":0,"val":"communications","end":""},{"old":"/api/v1/inspection/communications/global","type":0,"val":"global","end":""}],
    types: placeholder as Registry['inspections.send_global_communication']['types'],
  },
  'inspection.send_school_communication': {
    methods: ["POST"],
    pattern: '/api/v1/inspection/communications/school',
    tokens: [{"old":"/api/v1/inspection/communications/school","type":0,"val":"api","end":""},{"old":"/api/v1/inspection/communications/school","type":0,"val":"v1","end":""},{"old":"/api/v1/inspection/communications/school","type":0,"val":"inspection","end":""},{"old":"/api/v1/inspection/communications/school","type":0,"val":"communications","end":""},{"old":"/api/v1/inspection/communications/school","type":0,"val":"school","end":""}],
    types: placeholder as Registry['inspection.send_school_communication']['types'],
  },
  'inspections.get_global_stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/inspection/stats/global',
    tokens: [{"old":"/api/v1/inspection/stats/global","type":0,"val":"api","end":""},{"old":"/api/v1/inspection/stats/global","type":0,"val":"v1","end":""},{"old":"/api/v1/inspection/stats/global","type":0,"val":"inspection","end":""},{"old":"/api/v1/inspection/stats/global","type":0,"val":"stats","end":""},{"old":"/api/v1/inspection/stats/global","type":0,"val":"global","end":""}],
    types: placeholder as Registry['inspections.get_global_stats']['types'],
  },
  'inspections.generate_school_report': {
    methods: ["POST"],
    pattern: '/api/v1/inspection/reports/school',
    tokens: [{"old":"/api/v1/inspection/reports/school","type":0,"val":"api","end":""},{"old":"/api/v1/inspection/reports/school","type":0,"val":"v1","end":""},{"old":"/api/v1/inspection/reports/school","type":0,"val":"inspection","end":""},{"old":"/api/v1/inspection/reports/school","type":0,"val":"reports","end":""},{"old":"/api/v1/inspection/reports/school","type":0,"val":"school","end":""}],
    types: placeholder as Registry['inspections.generate_school_report']['types'],
  },
  'schools.dashboard': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/school/dashboard',
    tokens: [{"old":"/api/v1/school/dashboard","type":0,"val":"api","end":""},{"old":"/api/v1/school/dashboard","type":0,"val":"v1","end":""},{"old":"/api/v1/school/dashboard","type":0,"val":"school","end":""},{"old":"/api/v1/school/dashboard","type":0,"val":"dashboard","end":""}],
    types: placeholder as Registry['schools.dashboard']['types'],
  },
  'schools.update_school_profile': {
    methods: ["PUT"],
    pattern: '/api/v1/school/profile',
    tokens: [{"old":"/api/v1/school/profile","type":0,"val":"api","end":""},{"old":"/api/v1/school/profile","type":0,"val":"v1","end":""},{"old":"/api/v1/school/profile","type":0,"val":"school","end":""},{"old":"/api/v1/school/profile","type":0,"val":"profile","end":""}],
    types: placeholder as Registry['schools.update_school_profile']['types'],
  },
  'academics.get_classes': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/school/classes',
    tokens: [{"old":"/api/v1/school/classes","type":0,"val":"api","end":""},{"old":"/api/v1/school/classes","type":0,"val":"v1","end":""},{"old":"/api/v1/school/classes","type":0,"val":"school","end":""},{"old":"/api/v1/school/classes","type":0,"val":"classes","end":""}],
    types: placeholder as Registry['academics.get_classes']['types'],
  },
  'academics.create_class': {
    methods: ["POST"],
    pattern: '/api/v1/school/classes',
    tokens: [{"old":"/api/v1/school/classes","type":0,"val":"api","end":""},{"old":"/api/v1/school/classes","type":0,"val":"v1","end":""},{"old":"/api/v1/school/classes","type":0,"val":"school","end":""},{"old":"/api/v1/school/classes","type":0,"val":"classes","end":""}],
    types: placeholder as Registry['academics.create_class']['types'],
  },
  'academics.get_class_by_id': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/school/classes/:id',
    tokens: [{"old":"/api/v1/school/classes/:id","type":0,"val":"api","end":""},{"old":"/api/v1/school/classes/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/school/classes/:id","type":0,"val":"school","end":""},{"old":"/api/v1/school/classes/:id","type":0,"val":"classes","end":""},{"old":"/api/v1/school/classes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['academics.get_class_by_id']['types'],
  },
  'academics.update_class': {
    methods: ["PUT"],
    pattern: '/api/v1/school/classes/:id',
    tokens: [{"old":"/api/v1/school/classes/:id","type":0,"val":"api","end":""},{"old":"/api/v1/school/classes/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/school/classes/:id","type":0,"val":"school","end":""},{"old":"/api/v1/school/classes/:id","type":0,"val":"classes","end":""},{"old":"/api/v1/school/classes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['academics.update_class']['types'],
  },
  'academics.delete_class': {
    methods: ["DELETE"],
    pattern: '/api/v1/school/classes/:id',
    tokens: [{"old":"/api/v1/school/classes/:id","type":0,"val":"api","end":""},{"old":"/api/v1/school/classes/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/school/classes/:id","type":0,"val":"school","end":""},{"old":"/api/v1/school/classes/:id","type":0,"val":"classes","end":""},{"old":"/api/v1/school/classes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['academics.delete_class']['types'],
  },
  'academics.get_class_students': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/school/classes/:id/students',
    tokens: [{"old":"/api/v1/school/classes/:id/students","type":0,"val":"api","end":""},{"old":"/api/v1/school/classes/:id/students","type":0,"val":"v1","end":""},{"old":"/api/v1/school/classes/:id/students","type":0,"val":"school","end":""},{"old":"/api/v1/school/classes/:id/students","type":0,"val":"classes","end":""},{"old":"/api/v1/school/classes/:id/students","type":1,"val":"id","end":""},{"old":"/api/v1/school/classes/:id/students","type":0,"val":"students","end":""}],
    types: placeholder as Registry['academics.get_class_students']['types'],
  },
  'academics.get_subjects': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/school/subjects',
    tokens: [{"old":"/api/v1/school/subjects","type":0,"val":"api","end":""},{"old":"/api/v1/school/subjects","type":0,"val":"v1","end":""},{"old":"/api/v1/school/subjects","type":0,"val":"school","end":""},{"old":"/api/v1/school/subjects","type":0,"val":"subjects","end":""}],
    types: placeholder as Registry['academics.get_subjects']['types'],
  },
  'academics.create_subject': {
    methods: ["POST"],
    pattern: '/api/v1/school/subjects',
    tokens: [{"old":"/api/v1/school/subjects","type":0,"val":"api","end":""},{"old":"/api/v1/school/subjects","type":0,"val":"v1","end":""},{"old":"/api/v1/school/subjects","type":0,"val":"school","end":""},{"old":"/api/v1/school/subjects","type":0,"val":"subjects","end":""}],
    types: placeholder as Registry['academics.create_subject']['types'],
  },
  'academics.update_subject': {
    methods: ["PUT"],
    pattern: '/api/v1/school/subjects/:id',
    tokens: [{"old":"/api/v1/school/subjects/:id","type":0,"val":"api","end":""},{"old":"/api/v1/school/subjects/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/school/subjects/:id","type":0,"val":"school","end":""},{"old":"/api/v1/school/subjects/:id","type":0,"val":"subjects","end":""},{"old":"/api/v1/school/subjects/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['academics.update_subject']['types'],
  },
  'academics.delete_subject': {
    methods: ["DELETE"],
    pattern: '/api/v1/school/subjects/:id',
    tokens: [{"old":"/api/v1/school/subjects/:id","type":0,"val":"api","end":""},{"old":"/api/v1/school/subjects/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/school/subjects/:id","type":0,"val":"school","end":""},{"old":"/api/v1/school/subjects/:id","type":0,"val":"subjects","end":""},{"old":"/api/v1/school/subjects/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['academics.delete_subject']['types'],
  },
  'academics.get_class_subjects': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/school/classes/:classId/subjects',
    tokens: [{"old":"/api/v1/school/classes/:classId/subjects","type":0,"val":"api","end":""},{"old":"/api/v1/school/classes/:classId/subjects","type":0,"val":"v1","end":""},{"old":"/api/v1/school/classes/:classId/subjects","type":0,"val":"school","end":""},{"old":"/api/v1/school/classes/:classId/subjects","type":0,"val":"classes","end":""},{"old":"/api/v1/school/classes/:classId/subjects","type":1,"val":"classId","end":""},{"old":"/api/v1/school/classes/:classId/subjects","type":0,"val":"subjects","end":""}],
    types: placeholder as Registry['academics.get_class_subjects']['types'],
  },
  'academics.add_subject_to_class': {
    methods: ["POST"],
    pattern: '/api/v1/school/classes/:classId/subjects',
    tokens: [{"old":"/api/v1/school/classes/:classId/subjects","type":0,"val":"api","end":""},{"old":"/api/v1/school/classes/:classId/subjects","type":0,"val":"v1","end":""},{"old":"/api/v1/school/classes/:classId/subjects","type":0,"val":"school","end":""},{"old":"/api/v1/school/classes/:classId/subjects","type":0,"val":"classes","end":""},{"old":"/api/v1/school/classes/:classId/subjects","type":1,"val":"classId","end":""},{"old":"/api/v1/school/classes/:classId/subjects","type":0,"val":"subjects","end":""}],
    types: placeholder as Registry['academics.add_subject_to_class']['types'],
  },
  'academics.get_grades_by_class': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/school/classes/:classId/grades',
    tokens: [{"old":"/api/v1/school/classes/:classId/grades","type":0,"val":"api","end":""},{"old":"/api/v1/school/classes/:classId/grades","type":0,"val":"v1","end":""},{"old":"/api/v1/school/classes/:classId/grades","type":0,"val":"school","end":""},{"old":"/api/v1/school/classes/:classId/grades","type":0,"val":"classes","end":""},{"old":"/api/v1/school/classes/:classId/grades","type":1,"val":"classId","end":""},{"old":"/api/v1/school/classes/:classId/grades","type":0,"val":"grades","end":""}],
    types: placeholder as Registry['academics.get_grades_by_class']['types'],
  },
  'academics.get_grades_by_student': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/school/students/:studentId/grades',
    tokens: [{"old":"/api/v1/school/students/:studentId/grades","type":0,"val":"api","end":""},{"old":"/api/v1/school/students/:studentId/grades","type":0,"val":"v1","end":""},{"old":"/api/v1/school/students/:studentId/grades","type":0,"val":"school","end":""},{"old":"/api/v1/school/students/:studentId/grades","type":0,"val":"students","end":""},{"old":"/api/v1/school/students/:studentId/grades","type":1,"val":"studentId","end":""},{"old":"/api/v1/school/students/:studentId/grades","type":0,"val":"grades","end":""}],
    types: placeholder as Registry['academics.get_grades_by_student']['types'],
  },
  'academics.add_grade': {
    methods: ["POST"],
    pattern: '/api/v1/school/grades',
    tokens: [{"old":"/api/v1/school/grades","type":0,"val":"api","end":""},{"old":"/api/v1/school/grades","type":0,"val":"v1","end":""},{"old":"/api/v1/school/grades","type":0,"val":"school","end":""},{"old":"/api/v1/school/grades","type":0,"val":"grades","end":""}],
    types: placeholder as Registry['academics.add_grade']['types'],
  },
  'academics.update_grade': {
    methods: ["PUT"],
    pattern: '/api/v1/school/grades/:id',
    tokens: [{"old":"/api/v1/school/grades/:id","type":0,"val":"api","end":""},{"old":"/api/v1/school/grades/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/school/grades/:id","type":0,"val":"school","end":""},{"old":"/api/v1/school/grades/:id","type":0,"val":"grades","end":""},{"old":"/api/v1/school/grades/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['academics.update_grade']['types'],
  },
  'academics.delete_grade': {
    methods: ["DELETE"],
    pattern: '/api/v1/school/grades/:id',
    tokens: [{"old":"/api/v1/school/grades/:id","type":0,"val":"api","end":""},{"old":"/api/v1/school/grades/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/school/grades/:id","type":0,"val":"school","end":""},{"old":"/api/v1/school/grades/:id","type":0,"val":"grades","end":""},{"old":"/api/v1/school/grades/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['academics.delete_grade']['types'],
  },
  'academics.publish_grades': {
    methods: ["POST"],
    pattern: '/api/v1/school/grades/publish',
    tokens: [{"old":"/api/v1/school/grades/publish","type":0,"val":"api","end":""},{"old":"/api/v1/school/grades/publish","type":0,"val":"v1","end":""},{"old":"/api/v1/school/grades/publish","type":0,"val":"school","end":""},{"old":"/api/v1/school/grades/publish","type":0,"val":"grades","end":""},{"old":"/api/v1/school/grades/publish","type":0,"val":"publish","end":""}],
    types: placeholder as Registry['academics.publish_grades']['types'],
  },
  'schools.add_teacher': {
    methods: ["POST"],
    pattern: '/api/v1/school/teachers',
    tokens: [{"old":"/api/v1/school/teachers","type":0,"val":"api","end":""},{"old":"/api/v1/school/teachers","type":0,"val":"v1","end":""},{"old":"/api/v1/school/teachers","type":0,"val":"school","end":""},{"old":"/api/v1/school/teachers","type":0,"val":"teachers","end":""}],
    types: placeholder as Registry['schools.add_teacher']['types'],
  },
  'transfers.request_transfer': {
    methods: ["POST"],
    pattern: '/api/v1/school/transfers/request',
    tokens: [{"old":"/api/v1/school/transfers/request","type":0,"val":"api","end":""},{"old":"/api/v1/school/transfers/request","type":0,"val":"v1","end":""},{"old":"/api/v1/school/transfers/request","type":0,"val":"school","end":""},{"old":"/api/v1/school/transfers/request","type":0,"val":"transfers","end":""},{"old":"/api/v1/school/transfers/request","type":0,"val":"request","end":""}],
    types: placeholder as Registry['transfers.request_transfer']['types'],
  },
  'transfers.get_pending_transfers': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/school/transfers/pending',
    tokens: [{"old":"/api/v1/school/transfers/pending","type":0,"val":"api","end":""},{"old":"/api/v1/school/transfers/pending","type":0,"val":"v1","end":""},{"old":"/api/v1/school/transfers/pending","type":0,"val":"school","end":""},{"old":"/api/v1/school/transfers/pending","type":0,"val":"transfers","end":""},{"old":"/api/v1/school/transfers/pending","type":0,"val":"pending","end":""}],
    types: placeholder as Registry['transfers.get_pending_transfers']['types'],
  },
  'transfers.approve_transfer': {
    methods: ["POST"],
    pattern: '/api/v1/school/transfers/approve',
    tokens: [{"old":"/api/v1/school/transfers/approve","type":0,"val":"api","end":""},{"old":"/api/v1/school/transfers/approve","type":0,"val":"v1","end":""},{"old":"/api/v1/school/transfers/approve","type":0,"val":"school","end":""},{"old":"/api/v1/school/transfers/approve","type":0,"val":"transfers","end":""},{"old":"/api/v1/school/transfers/approve","type":0,"val":"approve","end":""}],
    types: placeholder as Registry['transfers.approve_transfer']['types'],
  },
  'transfers.reject_transfer': {
    methods: ["POST"],
    pattern: '/api/v1/school/transfers/reject',
    tokens: [{"old":"/api/v1/school/transfers/reject","type":0,"val":"api","end":""},{"old":"/api/v1/school/transfers/reject","type":0,"val":"v1","end":""},{"old":"/api/v1/school/transfers/reject","type":0,"val":"school","end":""},{"old":"/api/v1/school/transfers/reject","type":0,"val":"transfers","end":""},{"old":"/api/v1/school/transfers/reject","type":0,"val":"reject","end":""}],
    types: placeholder as Registry['transfers.reject_transfer']['types'],
  },
  'transfers.complete_transfer': {
    methods: ["POST"],
    pattern: '/api/v1/school/transfers/:id/complete',
    tokens: [{"old":"/api/v1/school/transfers/:id/complete","type":0,"val":"api","end":""},{"old":"/api/v1/school/transfers/:id/complete","type":0,"val":"v1","end":""},{"old":"/api/v1/school/transfers/:id/complete","type":0,"val":"school","end":""},{"old":"/api/v1/school/transfers/:id/complete","type":0,"val":"transfers","end":""},{"old":"/api/v1/school/transfers/:id/complete","type":1,"val":"id","end":""},{"old":"/api/v1/school/transfers/:id/complete","type":0,"val":"complete","end":""}],
    types: placeholder as Registry['transfers.complete_transfer']['types'],
  },
  'academics.get_academic_stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/school/stats/academic',
    tokens: [{"old":"/api/v1/school/stats/academic","type":0,"val":"api","end":""},{"old":"/api/v1/school/stats/academic","type":0,"val":"v1","end":""},{"old":"/api/v1/school/stats/academic","type":0,"val":"school","end":""},{"old":"/api/v1/school/stats/academic","type":0,"val":"stats","end":""},{"old":"/api/v1/school/stats/academic","type":0,"val":"academic","end":""}],
    types: placeholder as Registry['academics.get_academic_stats']['types'],
  },
  'academics.get_progress_stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/school/stats/progress',
    tokens: [{"old":"/api/v1/school/stats/progress","type":0,"val":"api","end":""},{"old":"/api/v1/school/stats/progress","type":0,"val":"v1","end":""},{"old":"/api/v1/school/stats/progress","type":0,"val":"school","end":""},{"old":"/api/v1/school/stats/progress","type":0,"val":"stats","end":""},{"old":"/api/v1/school/stats/progress","type":0,"val":"progress","end":""}],
    types: placeholder as Registry['academics.get_progress_stats']['types'],
  },
  'pedagogicals.generate_report_card': {
    methods: ["POST"],
    pattern: '/api/v1/pedagogical/report-cards/student',
    tokens: [{"old":"/api/v1/pedagogical/report-cards/student","type":0,"val":"api","end":""},{"old":"/api/v1/pedagogical/report-cards/student","type":0,"val":"v1","end":""},{"old":"/api/v1/pedagogical/report-cards/student","type":0,"val":"pedagogical","end":""},{"old":"/api/v1/pedagogical/report-cards/student","type":0,"val":"report-cards","end":""},{"old":"/api/v1/pedagogical/report-cards/student","type":0,"val":"student","end":""}],
    types: placeholder as Registry['pedagogicals.generate_report_card']['types'],
  },
  'pedagogicals.get_class_timetable': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/pedagogical/timetable/class/:classId',
    tokens: [{"old":"/api/v1/pedagogical/timetable/class/:classId","type":0,"val":"api","end":""},{"old":"/api/v1/pedagogical/timetable/class/:classId","type":0,"val":"v1","end":""},{"old":"/api/v1/pedagogical/timetable/class/:classId","type":0,"val":"pedagogical","end":""},{"old":"/api/v1/pedagogical/timetable/class/:classId","type":0,"val":"timetable","end":""},{"old":"/api/v1/pedagogical/timetable/class/:classId","type":0,"val":"class","end":""},{"old":"/api/v1/pedagogical/timetable/class/:classId","type":1,"val":"classId","end":""}],
    types: placeholder as Registry['pedagogicals.get_class_timetable']['types'],
  },
  'pedagogicals.create_timetable': {
    methods: ["POST"],
    pattern: '/api/v1/pedagogical/timetable',
    tokens: [{"old":"/api/v1/pedagogical/timetable","type":0,"val":"api","end":""},{"old":"/api/v1/pedagogical/timetable","type":0,"val":"v1","end":""},{"old":"/api/v1/pedagogical/timetable","type":0,"val":"pedagogical","end":""},{"old":"/api/v1/pedagogical/timetable","type":0,"val":"timetable","end":""}],
    types: placeholder as Registry['pedagogicals.create_timetable']['types'],
  },
  'pedagogicals.publish_grades': {
    methods: ["POST"],
    pattern: '/api/v1/pedagogical/grades/publish',
    tokens: [{"old":"/api/v1/pedagogical/grades/publish","type":0,"val":"api","end":""},{"old":"/api/v1/pedagogical/grades/publish","type":0,"val":"v1","end":""},{"old":"/api/v1/pedagogical/grades/publish","type":0,"val":"pedagogical","end":""},{"old":"/api/v1/pedagogical/grades/publish","type":0,"val":"grades","end":""},{"old":"/api/v1/pedagogical/grades/publish","type":0,"val":"publish","end":""}],
    types: placeholder as Registry['pedagogicals.publish_grades']['types'],
  },
  'pedagogicals.create_academic_calendar': {
    methods: ["POST"],
    pattern: '/api/v1/pedagogical/calendar',
    tokens: [{"old":"/api/v1/pedagogical/calendar","type":0,"val":"api","end":""},{"old":"/api/v1/pedagogical/calendar","type":0,"val":"v1","end":""},{"old":"/api/v1/pedagogical/calendar","type":0,"val":"pedagogical","end":""},{"old":"/api/v1/pedagogical/calendar","type":0,"val":"calendar","end":""}],
    types: placeholder as Registry['pedagogicals.create_academic_calendar']['types'],
  },
  'pedagogicals.create_exam_schedule': {
    methods: ["POST"],
    pattern: '/api/v1/pedagogical/exam-schedules',
    tokens: [{"old":"/api/v1/pedagogical/exam-schedules","type":0,"val":"api","end":""},{"old":"/api/v1/pedagogical/exam-schedules","type":0,"val":"v1","end":""},{"old":"/api/v1/pedagogical/exam-schedules","type":0,"val":"pedagogical","end":""},{"old":"/api/v1/pedagogical/exam-schedules","type":0,"val":"exam-schedules","end":""}],
    types: placeholder as Registry['pedagogicals.create_exam_schedule']['types'],
  },
  'pedagogicals.get_student_progress': {
    methods: ["POST"],
    pattern: '/api/v1/pedagogical/students/progress',
    tokens: [{"old":"/api/v1/pedagogical/students/progress","type":0,"val":"api","end":""},{"old":"/api/v1/pedagogical/students/progress","type":0,"val":"v1","end":""},{"old":"/api/v1/pedagogical/students/progress","type":0,"val":"pedagogical","end":""},{"old":"/api/v1/pedagogical/students/progress","type":0,"val":"students","end":""},{"old":"/api/v1/pedagogical/students/progress","type":0,"val":"progress","end":""}],
    types: placeholder as Registry['pedagogicals.get_student_progress']['types'],
  },
  'financials.get_fees': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/financial/fees',
    tokens: [{"old":"/api/v1/financial/fees","type":0,"val":"api","end":""},{"old":"/api/v1/financial/fees","type":0,"val":"v1","end":""},{"old":"/api/v1/financial/fees","type":0,"val":"financial","end":""},{"old":"/api/v1/financial/fees","type":0,"val":"fees","end":""}],
    types: placeholder as Registry['financials.get_fees']['types'],
  },
  'financials.set_fees': {
    methods: ["POST"],
    pattern: '/api/v1/financial/fees',
    tokens: [{"old":"/api/v1/financial/fees","type":0,"val":"api","end":""},{"old":"/api/v1/financial/fees","type":0,"val":"v1","end":""},{"old":"/api/v1/financial/fees","type":0,"val":"financial","end":""},{"old":"/api/v1/financial/fees","type":0,"val":"fees","end":""}],
    types: placeholder as Registry['financials.set_fees']['types'],
  },
  'financials.update_fees': {
    methods: ["PUT"],
    pattern: '/api/v1/financial/fees/:id',
    tokens: [{"old":"/api/v1/financial/fees/:id","type":0,"val":"api","end":""},{"old":"/api/v1/financial/fees/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/financial/fees/:id","type":0,"val":"financial","end":""},{"old":"/api/v1/financial/fees/:id","type":0,"val":"fees","end":""},{"old":"/api/v1/financial/fees/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['financials.update_fees']['types'],
  },
  'financials.delete_fees': {
    methods: ["DELETE"],
    pattern: '/api/v1/financial/fees/:id',
    tokens: [{"old":"/api/v1/financial/fees/:id","type":0,"val":"api","end":""},{"old":"/api/v1/financial/fees/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/financial/fees/:id","type":0,"val":"financial","end":""},{"old":"/api/v1/financial/fees/:id","type":0,"val":"fees","end":""},{"old":"/api/v1/financial/fees/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['financials.delete_fees']['types'],
  },
  'financials.record_payment': {
    methods: ["POST"],
    pattern: '/api/v1/financial/payments',
    tokens: [{"old":"/api/v1/financial/payments","type":0,"val":"api","end":""},{"old":"/api/v1/financial/payments","type":0,"val":"v1","end":""},{"old":"/api/v1/financial/payments","type":0,"val":"financial","end":""},{"old":"/api/v1/financial/payments","type":0,"val":"payments","end":""}],
    types: placeholder as Registry['financials.record_payment']['types'],
  },
  'financials.get_student_payments': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/financial/payments/student/:studentId',
    tokens: [{"old":"/api/v1/financial/payments/student/:studentId","type":0,"val":"api","end":""},{"old":"/api/v1/financial/payments/student/:studentId","type":0,"val":"v1","end":""},{"old":"/api/v1/financial/payments/student/:studentId","type":0,"val":"financial","end":""},{"old":"/api/v1/financial/payments/student/:studentId","type":0,"val":"payments","end":""},{"old":"/api/v1/financial/payments/student/:studentId","type":0,"val":"student","end":""},{"old":"/api/v1/financial/payments/student/:studentId","type":1,"val":"studentId","end":""}],
    types: placeholder as Registry['financials.get_student_payments']['types'],
  },
  'financials.get_income_report': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/financial/reports/income',
    tokens: [{"old":"/api/v1/financial/reports/income","type":0,"val":"api","end":""},{"old":"/api/v1/financial/reports/income","type":0,"val":"v1","end":""},{"old":"/api/v1/financial/reports/income","type":0,"val":"financial","end":""},{"old":"/api/v1/financial/reports/income","type":0,"val":"reports","end":""},{"old":"/api/v1/financial/reports/income","type":0,"val":"income","end":""}],
    types: placeholder as Registry['financials.get_income_report']['types'],
  },
  'financials.get_financial_stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/financial/stats/financial',
    tokens: [{"old":"/api/v1/financial/stats/financial","type":0,"val":"api","end":""},{"old":"/api/v1/financial/stats/financial","type":0,"val":"v1","end":""},{"old":"/api/v1/financial/stats/financial","type":0,"val":"financial","end":""},{"old":"/api/v1/financial/stats/financial","type":0,"val":"stats","end":""},{"old":"/api/v1/financial/stats/financial","type":0,"val":"financial","end":""}],
    types: placeholder as Registry['financials.get_financial_stats']['types'],
  },
  'teachers.get_my_classes': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/teacher/my-classes',
    tokens: [{"old":"/api/v1/teacher/my-classes","type":0,"val":"api","end":""},{"old":"/api/v1/teacher/my-classes","type":0,"val":"v1","end":""},{"old":"/api/v1/teacher/my-classes","type":0,"val":"teacher","end":""},{"old":"/api/v1/teacher/my-classes","type":0,"val":"my-classes","end":""}],
    types: placeholder as Registry['teachers.get_my_classes']['types'],
  },
  'teachers.get_assignments': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/teacher/assignments',
    tokens: [{"old":"/api/v1/teacher/assignments","type":0,"val":"api","end":""},{"old":"/api/v1/teacher/assignments","type":0,"val":"v1","end":""},{"old":"/api/v1/teacher/assignments","type":0,"val":"teacher","end":""},{"old":"/api/v1/teacher/assignments","type":0,"val":"assignments","end":""}],
    types: placeholder as Registry['teachers.get_assignments']['types'],
  },
  'teachers.create_assignment': {
    methods: ["POST"],
    pattern: '/api/v1/teacher/assignments',
    tokens: [{"old":"/api/v1/teacher/assignments","type":0,"val":"api","end":""},{"old":"/api/v1/teacher/assignments","type":0,"val":"v1","end":""},{"old":"/api/v1/teacher/assignments","type":0,"val":"teacher","end":""},{"old":"/api/v1/teacher/assignments","type":0,"val":"assignments","end":""}],
    types: placeholder as Registry['teachers.create_assignment']['types'],
  },
  'teachers.grade_submission': {
    methods: ["POST"],
    pattern: '/api/v1/teacher/assignments/submissions/:id/grade',
    tokens: [{"old":"/api/v1/teacher/assignments/submissions/:id/grade","type":0,"val":"api","end":""},{"old":"/api/v1/teacher/assignments/submissions/:id/grade","type":0,"val":"v1","end":""},{"old":"/api/v1/teacher/assignments/submissions/:id/grade","type":0,"val":"teacher","end":""},{"old":"/api/v1/teacher/assignments/submissions/:id/grade","type":0,"val":"assignments","end":""},{"old":"/api/v1/teacher/assignments/submissions/:id/grade","type":0,"val":"submissions","end":""},{"old":"/api/v1/teacher/assignments/submissions/:id/grade","type":1,"val":"id","end":""},{"old":"/api/v1/teacher/assignments/submissions/:id/grade","type":0,"val":"grade","end":""}],
    types: placeholder as Registry['teachers.grade_submission']['types'],
  },
  'teachers.create_forum_topic': {
    methods: ["POST"],
    pattern: '/api/v1/teacher/forum/topics',
    tokens: [{"old":"/api/v1/teacher/forum/topics","type":0,"val":"api","end":""},{"old":"/api/v1/teacher/forum/topics","type":0,"val":"v1","end":""},{"old":"/api/v1/teacher/forum/topics","type":0,"val":"teacher","end":""},{"old":"/api/v1/teacher/forum/topics","type":0,"val":"forum","end":""},{"old":"/api/v1/teacher/forum/topics","type":0,"val":"topics","end":""}],
    types: placeholder as Registry['teachers.create_forum_topic']['types'],
  },
  'teachers.mark_attendance': {
    methods: ["POST"],
    pattern: '/api/v1/teacher/attendance',
    tokens: [{"old":"/api/v1/teacher/attendance","type":0,"val":"api","end":""},{"old":"/api/v1/teacher/attendance","type":0,"val":"v1","end":""},{"old":"/api/v1/teacher/attendance","type":0,"val":"teacher","end":""},{"old":"/api/v1/teacher/attendance","type":0,"val":"attendance","end":""}],
    types: placeholder as Registry['teachers.mark_attendance']['types'],
  },
  'parents.get_children': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/parent/children',
    tokens: [{"old":"/api/v1/parent/children","type":0,"val":"api","end":""},{"old":"/api/v1/parent/children","type":0,"val":"v1","end":""},{"old":"/api/v1/parent/children","type":0,"val":"parent","end":""},{"old":"/api/v1/parent/children","type":0,"val":"children","end":""}],
    types: placeholder as Registry['parents.get_children']['types'],
  },
  'parents.get_child_grades': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/parent/grades/child/:studentId',
    tokens: [{"old":"/api/v1/parent/grades/child/:studentId","type":0,"val":"api","end":""},{"old":"/api/v1/parent/grades/child/:studentId","type":0,"val":"v1","end":""},{"old":"/api/v1/parent/grades/child/:studentId","type":0,"val":"parent","end":""},{"old":"/api/v1/parent/grades/child/:studentId","type":0,"val":"grades","end":""},{"old":"/api/v1/parent/grades/child/:studentId","type":0,"val":"child","end":""},{"old":"/api/v1/parent/grades/child/:studentId","type":1,"val":"studentId","end":""}],
    types: placeholder as Registry['parents.get_child_grades']['types'],
  },
  'parents.send_message_to_teacher': {
    methods: ["POST"],
    pattern: '/api/v1/parent/messages/teacher',
    tokens: [{"old":"/api/v1/parent/messages/teacher","type":0,"val":"api","end":""},{"old":"/api/v1/parent/messages/teacher","type":0,"val":"v1","end":""},{"old":"/api/v1/parent/messages/teacher","type":0,"val":"parent","end":""},{"old":"/api/v1/parent/messages/teacher","type":0,"val":"messages","end":""},{"old":"/api/v1/parent/messages/teacher","type":0,"val":"teacher","end":""}],
    types: placeholder as Registry['parents.send_message_to_teacher']['types'],
  },
  'parents.get_child_payments': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/parent/payments/child/:studentId',
    tokens: [{"old":"/api/v1/parent/payments/child/:studentId","type":0,"val":"api","end":""},{"old":"/api/v1/parent/payments/child/:studentId","type":0,"val":"v1","end":""},{"old":"/api/v1/parent/payments/child/:studentId","type":0,"val":"parent","end":""},{"old":"/api/v1/parent/payments/child/:studentId","type":0,"val":"payments","end":""},{"old":"/api/v1/parent/payments/child/:studentId","type":0,"val":"child","end":""},{"old":"/api/v1/parent/payments/child/:studentId","type":1,"val":"studentId","end":""}],
    types: placeholder as Registry['parents.get_child_payments']['types'],
  },
  'parents.justify_absence': {
    methods: ["POST"],
    pattern: '/api/v1/parent/absence/justify',
    tokens: [{"old":"/api/v1/parent/absence/justify","type":0,"val":"api","end":""},{"old":"/api/v1/parent/absence/justify","type":0,"val":"v1","end":""},{"old":"/api/v1/parent/absence/justify","type":0,"val":"parent","end":""},{"old":"/api/v1/parent/absence/justify","type":0,"val":"absence","end":""},{"old":"/api/v1/parent/absence/justify","type":0,"val":"justify","end":""}],
    types: placeholder as Registry['parents.justify_absence']['types'],
  },
  'students.get_my_profile': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/student/my-profile',
    tokens: [{"old":"/api/v1/student/my-profile","type":0,"val":"api","end":""},{"old":"/api/v1/student/my-profile","type":0,"val":"v1","end":""},{"old":"/api/v1/student/my-profile","type":0,"val":"student","end":""},{"old":"/api/v1/student/my-profile","type":0,"val":"my-profile","end":""}],
    types: placeholder as Registry['students.get_my_profile']['types'],
  },
  'students.get_my_grades': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/student/my-grades',
    tokens: [{"old":"/api/v1/student/my-grades","type":0,"val":"api","end":""},{"old":"/api/v1/student/my-grades","type":0,"val":"v1","end":""},{"old":"/api/v1/student/my-grades","type":0,"val":"student","end":""},{"old":"/api/v1/student/my-grades","type":0,"val":"my-grades","end":""}],
    types: placeholder as Registry['students.get_my_grades']['types'],
  },
  'students.get_my_report_card': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/student/my-report-card',
    tokens: [{"old":"/api/v1/student/my-report-card","type":0,"val":"api","end":""},{"old":"/api/v1/student/my-report-card","type":0,"val":"v1","end":""},{"old":"/api/v1/student/my-report-card","type":0,"val":"student","end":""},{"old":"/api/v1/student/my-report-card","type":0,"val":"my-report-card","end":""}],
    types: placeholder as Registry['students.get_my_report_card']['types'],
  },
  'students.get_my_discipline': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/student/my-discipline',
    tokens: [{"old":"/api/v1/student/my-discipline","type":0,"val":"api","end":""},{"old":"/api/v1/student/my-discipline","type":0,"val":"v1","end":""},{"old":"/api/v1/student/my-discipline","type":0,"val":"student","end":""},{"old":"/api/v1/student/my-discipline","type":0,"val":"my-discipline","end":""}],
    types: placeholder as Registry['students.get_my_discipline']['types'],
  },
  'students.get_assignments': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/student/assignments',
    tokens: [{"old":"/api/v1/student/assignments","type":0,"val":"api","end":""},{"old":"/api/v1/student/assignments","type":0,"val":"v1","end":""},{"old":"/api/v1/student/assignments","type":0,"val":"student","end":""},{"old":"/api/v1/student/assignments","type":0,"val":"assignments","end":""}],
    types: placeholder as Registry['students.get_assignments']['types'],
  },
  'students.submit_assignment': {
    methods: ["POST"],
    pattern: '/api/v1/student/assignments/submit',
    tokens: [{"old":"/api/v1/student/assignments/submit","type":0,"val":"api","end":""},{"old":"/api/v1/student/assignments/submit","type":0,"val":"v1","end":""},{"old":"/api/v1/student/assignments/submit","type":0,"val":"student","end":""},{"old":"/api/v1/student/assignments/submit","type":0,"val":"assignments","end":""},{"old":"/api/v1/student/assignments/submit","type":0,"val":"submit","end":""}],
    types: placeholder as Registry['students.submit_assignment']['types'],
  },
  'students.get_my_forum_questions': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/student/forum/questions',
    tokens: [{"old":"/api/v1/student/forum/questions","type":0,"val":"api","end":""},{"old":"/api/v1/student/forum/questions","type":0,"val":"v1","end":""},{"old":"/api/v1/student/forum/questions","type":0,"val":"student","end":""},{"old":"/api/v1/student/forum/questions","type":0,"val":"forum","end":""},{"old":"/api/v1/student/forum/questions","type":0,"val":"questions","end":""}],
    types: placeholder as Registry['students.get_my_forum_questions']['types'],
  },
  'students.post_forum_question': {
    methods: ["POST"],
    pattern: '/api/v1/student/forum/questions',
    tokens: [{"old":"/api/v1/student/forum/questions","type":0,"val":"api","end":""},{"old":"/api/v1/student/forum/questions","type":0,"val":"v1","end":""},{"old":"/api/v1/student/forum/questions","type":0,"val":"student","end":""},{"old":"/api/v1/student/forum/questions","type":0,"val":"forum","end":""},{"old":"/api/v1/student/forum/questions","type":0,"val":"questions","end":""}],
    types: placeholder as Registry['students.post_forum_question']['types'],
  },
  'students.send_message_to_teacher': {
    methods: ["POST"],
    pattern: '/api/v1/student/messages/teacher',
    tokens: [{"old":"/api/v1/student/messages/teacher","type":0,"val":"api","end":""},{"old":"/api/v1/student/messages/teacher","type":0,"val":"v1","end":""},{"old":"/api/v1/student/messages/teacher","type":0,"val":"student","end":""},{"old":"/api/v1/student/messages/teacher","type":0,"val":"messages","end":""},{"old":"/api/v1/student/messages/teacher","type":0,"val":"teacher","end":""}],
    types: placeholder as Registry['students.send_message_to_teacher']['types'],
  },
  'students.get_my_timetable': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/student/timetable',
    tokens: [{"old":"/api/v1/student/timetable","type":0,"val":"api","end":""},{"old":"/api/v1/student/timetable","type":0,"val":"v1","end":""},{"old":"/api/v1/student/timetable","type":0,"val":"student","end":""},{"old":"/api/v1/student/timetable","type":0,"val":"timetable","end":""}],
    types: placeholder as Registry['students.get_my_timetable']['types'],
  },
  'students.get_my_attendance': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/student/attendance',
    tokens: [{"old":"/api/v1/student/attendance","type":0,"val":"api","end":""},{"old":"/api/v1/student/attendance","type":0,"val":"v1","end":""},{"old":"/api/v1/student/attendance","type":0,"val":"student","end":""},{"old":"/api/v1/student/attendance","type":0,"val":"attendance","end":""}],
    types: placeholder as Registry['students.get_my_attendance']['types'],
  },
  'students.request_transfer': {
    methods: ["POST"],
    pattern: '/api/v1/student/transfers/request',
    tokens: [{"old":"/api/v1/student/transfers/request","type":0,"val":"api","end":""},{"old":"/api/v1/student/transfers/request","type":0,"val":"v1","end":""},{"old":"/api/v1/student/transfers/request","type":0,"val":"student","end":""},{"old":"/api/v1/student/transfers/request","type":0,"val":"transfers","end":""},{"old":"/api/v1/student/transfers/request","type":0,"val":"request","end":""}],
    types: placeholder as Registry['students.request_transfer']['types'],
  },
  'disciplines.get_students': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/discipline/students',
    tokens: [{"old":"/api/v1/discipline/students","type":0,"val":"api","end":""},{"old":"/api/v1/discipline/students","type":0,"val":"v1","end":""},{"old":"/api/v1/discipline/students","type":0,"val":"discipline","end":""},{"old":"/api/v1/discipline/students","type":0,"val":"students","end":""}],
    types: placeholder as Registry['disciplines.get_students']['types'],
  },
  'disciplines.get_student_details': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/discipline/students/:id',
    tokens: [{"old":"/api/v1/discipline/students/:id","type":0,"val":"api","end":""},{"old":"/api/v1/discipline/students/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/discipline/students/:id","type":0,"val":"discipline","end":""},{"old":"/api/v1/discipline/students/:id","type":0,"val":"students","end":""},{"old":"/api/v1/discipline/students/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['disciplines.get_student_details']['types'],
  },
  'disciplines.report_incident': {
    methods: ["POST"],
    pattern: '/api/v1/discipline/incidents',
    tokens: [{"old":"/api/v1/discipline/incidents","type":0,"val":"api","end":""},{"old":"/api/v1/discipline/incidents","type":0,"val":"v1","end":""},{"old":"/api/v1/discipline/incidents","type":0,"val":"discipline","end":""},{"old":"/api/v1/discipline/incidents","type":0,"val":"incidents","end":""}],
    types: placeholder as Registry['disciplines.report_incident']['types'],
  },
  'disciplines.delete_incident': {
    methods: ["DELETE"],
    pattern: '/api/v1/discipline/incidents/:id',
    tokens: [{"old":"/api/v1/discipline/incidents/:id","type":0,"val":"api","end":""},{"old":"/api/v1/discipline/incidents/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/discipline/incidents/:id","type":0,"val":"discipline","end":""},{"old":"/api/v1/discipline/incidents/:id","type":0,"val":"incidents","end":""},{"old":"/api/v1/discipline/incidents/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['disciplines.delete_incident']['types'],
  },
  'disciplines.apply_sanction': {
    methods: ["POST"],
    pattern: '/api/v1/discipline/sanctions',
    tokens: [{"old":"/api/v1/discipline/sanctions","type":0,"val":"api","end":""},{"old":"/api/v1/discipline/sanctions","type":0,"val":"v1","end":""},{"old":"/api/v1/discipline/sanctions","type":0,"val":"discipline","end":""},{"old":"/api/v1/discipline/sanctions","type":0,"val":"sanctions","end":""}],
    types: placeholder as Registry['disciplines.apply_sanction']['types'],
  },
  'disciplines.notify_parent': {
    methods: ["POST"],
    pattern: '/api/v1/discipline/notify-parent',
    tokens: [{"old":"/api/v1/discipline/notify-parent","type":0,"val":"api","end":""},{"old":"/api/v1/discipline/notify-parent","type":0,"val":"v1","end":""},{"old":"/api/v1/discipline/notify-parent","type":0,"val":"discipline","end":""},{"old":"/api/v1/discipline/notify-parent","type":0,"val":"notify-parent","end":""}],
    types: placeholder as Registry['disciplines.notify_parent']['types'],
  },
  'messages.get_messages': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/communication/messages',
    tokens: [{"old":"/api/v1/communication/messages","type":0,"val":"api","end":""},{"old":"/api/v1/communication/messages","type":0,"val":"v1","end":""},{"old":"/api/v1/communication/messages","type":0,"val":"communication","end":""},{"old":"/api/v1/communication/messages","type":0,"val":"messages","end":""}],
    types: placeholder as Registry['messages.get_messages']['types'],
  },
  'messages.send_message': {
    methods: ["POST"],
    pattern: '/api/v1/communication/messages/send',
    tokens: [{"old":"/api/v1/communication/messages/send","type":0,"val":"api","end":""},{"old":"/api/v1/communication/messages/send","type":0,"val":"v1","end":""},{"old":"/api/v1/communication/messages/send","type":0,"val":"communication","end":""},{"old":"/api/v1/communication/messages/send","type":0,"val":"messages","end":""},{"old":"/api/v1/communication/messages/send","type":0,"val":"send","end":""}],
    types: placeholder as Registry['messages.send_message']['types'],
  },
  'messages.mark_as_read': {
    methods: ["PUT"],
    pattern: '/api/v1/communication/messages/read',
    tokens: [{"old":"/api/v1/communication/messages/read","type":0,"val":"api","end":""},{"old":"/api/v1/communication/messages/read","type":0,"val":"v1","end":""},{"old":"/api/v1/communication/messages/read","type":0,"val":"communication","end":""},{"old":"/api/v1/communication/messages/read","type":0,"val":"messages","end":""},{"old":"/api/v1/communication/messages/read","type":0,"val":"read","end":""}],
    types: placeholder as Registry['messages.mark_as_read']['types'],
  },
  'messages.get_conversations': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/communication/conversations',
    tokens: [{"old":"/api/v1/communication/conversations","type":0,"val":"api","end":""},{"old":"/api/v1/communication/conversations","type":0,"val":"v1","end":""},{"old":"/api/v1/communication/conversations","type":0,"val":"communication","end":""},{"old":"/api/v1/communication/conversations","type":0,"val":"conversations","end":""}],
    types: placeholder as Registry['messages.get_conversations']['types'],
  },
  'messages.get_conversation': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/communication/conversations/:userId',
    tokens: [{"old":"/api/v1/communication/conversations/:userId","type":0,"val":"api","end":""},{"old":"/api/v1/communication/conversations/:userId","type":0,"val":"v1","end":""},{"old":"/api/v1/communication/conversations/:userId","type":0,"val":"communication","end":""},{"old":"/api/v1/communication/conversations/:userId","type":0,"val":"conversations","end":""},{"old":"/api/v1/communication/conversations/:userId","type":1,"val":"userId","end":""}],
    types: placeholder as Registry['messages.get_conversation']['types'],
  },
  'communication.send_global_communication': {
    methods: ["POST"],
    pattern: '/api/v1/communication/communications/global',
    tokens: [{"old":"/api/v1/communication/communications/global","type":0,"val":"api","end":""},{"old":"/api/v1/communication/communications/global","type":0,"val":"v1","end":""},{"old":"/api/v1/communication/communications/global","type":0,"val":"communication","end":""},{"old":"/api/v1/communication/communications/global","type":0,"val":"communications","end":""},{"old":"/api/v1/communication/communications/global","type":0,"val":"global","end":""}],
    types: placeholder as Registry['communication.send_global_communication']['types'],
  },
  'communication.send_school_communication': {
    methods: ["POST"],
    pattern: '/api/v1/communication/communications/school',
    tokens: [{"old":"/api/v1/communication/communications/school","type":0,"val":"api","end":""},{"old":"/api/v1/communication/communications/school","type":0,"val":"v1","end":""},{"old":"/api/v1/communication/communications/school","type":0,"val":"communication","end":""},{"old":"/api/v1/communication/communications/school","type":0,"val":"communications","end":""},{"old":"/api/v1/communication/communications/school","type":0,"val":"school","end":""}],
    types: placeholder as Registry['communication.send_school_communication']['types'],
  },
  'inter_schools.search_schools': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/inter-school/search',
    tokens: [{"old":"/api/v1/inter-school/search","type":0,"val":"api","end":""},{"old":"/api/v1/inter-school/search","type":0,"val":"v1","end":""},{"old":"/api/v1/inter-school/search","type":0,"val":"inter-school","end":""},{"old":"/api/v1/inter-school/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['inter_schools.search_schools']['types'],
  },
  'inter_schools.get_school_public_info': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/inter-school/:id/info',
    tokens: [{"old":"/api/v1/inter-school/:id/info","type":0,"val":"api","end":""},{"old":"/api/v1/inter-school/:id/info","type":0,"val":"v1","end":""},{"old":"/api/v1/inter-school/:id/info","type":0,"val":"inter-school","end":""},{"old":"/api/v1/inter-school/:id/info","type":1,"val":"id","end":""},{"old":"/api/v1/inter-school/:id/info","type":0,"val":"info","end":""}],
    types: placeholder as Registry['inter_schools.get_school_public_info']['types'],
  },
  'inter_schools.start_exchange': {
    methods: ["POST"],
    pattern: '/api/v1/inter-school/exchanges',
    tokens: [{"old":"/api/v1/inter-school/exchanges","type":0,"val":"api","end":""},{"old":"/api/v1/inter-school/exchanges","type":0,"val":"v1","end":""},{"old":"/api/v1/inter-school/exchanges","type":0,"val":"inter-school","end":""},{"old":"/api/v1/inter-school/exchanges","type":0,"val":"exchanges","end":""}],
    types: placeholder as Registry['inter_schools.start_exchange']['types'],
  },
  'inter_schools.get_best_practices': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/inter-school/best-practices',
    tokens: [{"old":"/api/v1/inter-school/best-practices","type":0,"val":"api","end":""},{"old":"/api/v1/inter-school/best-practices","type":0,"val":"v1","end":""},{"old":"/api/v1/inter-school/best-practices","type":0,"val":"inter-school","end":""},{"old":"/api/v1/inter-school/best-practices","type":0,"val":"best-practices","end":""}],
    types: placeholder as Registry['inter_schools.get_best_practices']['types'],
  },
  'inter_schools.share_best_practice': {
    methods: ["POST"],
    pattern: '/api/v1/inter-school/best-practices/share',
    tokens: [{"old":"/api/v1/inter-school/best-practices/share","type":0,"val":"api","end":""},{"old":"/api/v1/inter-school/best-practices/share","type":0,"val":"v1","end":""},{"old":"/api/v1/inter-school/best-practices/share","type":0,"val":"inter-school","end":""},{"old":"/api/v1/inter-school/best-practices/share","type":0,"val":"best-practices","end":""},{"old":"/api/v1/inter-school/best-practices/share","type":0,"val":"share","end":""}],
    types: placeholder as Registry['inter_schools.share_best_practice']['types'],
  },
  'inter_schools.get_events': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/inter-school/events',
    tokens: [{"old":"/api/v1/inter-school/events","type":0,"val":"api","end":""},{"old":"/api/v1/inter-school/events","type":0,"val":"v1","end":""},{"old":"/api/v1/inter-school/events","type":0,"val":"inter-school","end":""},{"old":"/api/v1/inter-school/events","type":0,"val":"events","end":""}],
    types: placeholder as Registry['inter_schools.get_events']['types'],
  },
  'inter_schools.create_event': {
    methods: ["POST"],
    pattern: '/api/v1/inter-school/events',
    tokens: [{"old":"/api/v1/inter-school/events","type":0,"val":"api","end":""},{"old":"/api/v1/inter-school/events","type":0,"val":"v1","end":""},{"old":"/api/v1/inter-school/events","type":0,"val":"inter-school","end":""},{"old":"/api/v1/inter-school/events","type":0,"val":"events","end":""}],
    types: placeholder as Registry['inter_schools.create_event']['types'],
  },
  'inter_schools.join_event': {
    methods: ["POST"],
    pattern: '/api/v1/inter-school/events/join',
    tokens: [{"old":"/api/v1/inter-school/events/join","type":0,"val":"api","end":""},{"old":"/api/v1/inter-school/events/join","type":0,"val":"v1","end":""},{"old":"/api/v1/inter-school/events/join","type":0,"val":"inter-school","end":""},{"old":"/api/v1/inter-school/events/join","type":0,"val":"events","end":""},{"old":"/api/v1/inter-school/events/join","type":0,"val":"join","end":""}],
    types: placeholder as Registry['inter_schools.join_event']['types'],
  },
  'admin.get_users': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/users',
    tokens: [{"old":"/api/v1/admin/users","type":0,"val":"api","end":""},{"old":"/api/v1/admin/users","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/users","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['admin.get_users']['types'],
  },
  'admin.create_user': {
    methods: ["POST"],
    pattern: '/api/v1/admin/users',
    tokens: [{"old":"/api/v1/admin/users","type":0,"val":"api","end":""},{"old":"/api/v1/admin/users","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/users","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['admin.create_user']['types'],
  },
  'admin.update_user': {
    methods: ["PUT"],
    pattern: '/api/v1/admin/users/:id',
    tokens: [{"old":"/api/v1/admin/users/:id","type":0,"val":"api","end":""},{"old":"/api/v1/admin/users/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/users/:id","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/users/:id","type":0,"val":"users","end":""},{"old":"/api/v1/admin/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.update_user']['types'],
  },
  'admin.delete_user': {
    methods: ["DELETE"],
    pattern: '/api/v1/admin/users/:id',
    tokens: [{"old":"/api/v1/admin/users/:id","type":0,"val":"api","end":""},{"old":"/api/v1/admin/users/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/users/:id","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/users/:id","type":0,"val":"users","end":""},{"old":"/api/v1/admin/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.delete_user']['types'],
  },
  'admin.activate_user': {
    methods: ["POST"],
    pattern: '/api/v1/admin/users/:id/activate',
    tokens: [{"old":"/api/v1/admin/users/:id/activate","type":0,"val":"api","end":""},{"old":"/api/v1/admin/users/:id/activate","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/users/:id/activate","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/users/:id/activate","type":0,"val":"users","end":""},{"old":"/api/v1/admin/users/:id/activate","type":1,"val":"id","end":""},{"old":"/api/v1/admin/users/:id/activate","type":0,"val":"activate","end":""}],
    types: placeholder as Registry['admin.activate_user']['types'],
  },
  'admin.suspend_user': {
    methods: ["POST"],
    pattern: '/api/v1/admin/users/:id/suspend',
    tokens: [{"old":"/api/v1/admin/users/:id/suspend","type":0,"val":"api","end":""},{"old":"/api/v1/admin/users/:id/suspend","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/users/:id/suspend","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/users/:id/suspend","type":0,"val":"users","end":""},{"old":"/api/v1/admin/users/:id/suspend","type":1,"val":"id","end":""},{"old":"/api/v1/admin/users/:id/suspend","type":0,"val":"suspend","end":""}],
    types: placeholder as Registry['admin.suspend_user']['types'],
  },
  'admin.get_roles': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/roles',
    tokens: [{"old":"/api/v1/admin/roles","type":0,"val":"api","end":""},{"old":"/api/v1/admin/roles","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/roles","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/roles","type":0,"val":"roles","end":""}],
    types: placeholder as Registry['admin.get_roles']['types'],
  },
  'admin.create_role': {
    methods: ["POST"],
    pattern: '/api/v1/admin/roles',
    tokens: [{"old":"/api/v1/admin/roles","type":0,"val":"api","end":""},{"old":"/api/v1/admin/roles","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/roles","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/roles","type":0,"val":"roles","end":""}],
    types: placeholder as Registry['admin.create_role']['types'],
  },
  'admin.update_role': {
    methods: ["PUT"],
    pattern: '/api/v1/admin/roles/:id',
    tokens: [{"old":"/api/v1/admin/roles/:id","type":0,"val":"api","end":""},{"old":"/api/v1/admin/roles/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/roles/:id","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/roles/:id","type":0,"val":"roles","end":""},{"old":"/api/v1/admin/roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.update_role']['types'],
  },
  'admin.get_system_logs': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/logs',
    tokens: [{"old":"/api/v1/admin/logs","type":0,"val":"api","end":""},{"old":"/api/v1/admin/logs","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/logs","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/logs","type":0,"val":"logs","end":""}],
    types: placeholder as Registry['admin.get_system_logs']['types'],
  },
  'admin.get_user_activity_logs': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/logs/users',
    tokens: [{"old":"/api/v1/admin/logs/users","type":0,"val":"api","end":""},{"old":"/api/v1/admin/logs/users","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/logs/users","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/logs/users","type":0,"val":"logs","end":""},{"old":"/api/v1/admin/logs/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['admin.get_user_activity_logs']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
