/* eslint-disable prettier/prettier */
import type { routes } from './index.ts'

export interface ApiDefinition {
  schools: {
    registerSchool: typeof routes['schools.register_school']
    dashboard: typeof routes['schools.dashboard']
    getSchoolStats: typeof routes['schools.get_school_stats']
    getSchoolProfile: typeof routes['schools.get_school_profile']
    updateSchoolProfile: typeof routes['schools.update_school_profile']
    getTeachers: typeof routes['schools.get_teachers']
    addTeacher: typeof routes['schools.add_teacher']
    updateTeacher: typeof routes['schools.update_teacher']
    removeTeacher: typeof routes['schools.remove_teacher']
  }
  auth: {
    login: typeof routes['auth.login']
    forgotPassword: typeof routes['auth.forgot_password']
    resetPassword: typeof routes['auth.reset_password']
    logout: typeof routes['auth.logout']
    changePassword: typeof routes['auth.change_password']
    getProfile: typeof routes['auth.get_profile']
    updateProfile: typeof routes['auth.update_profile']
  }
  transfers: {
    verifyAuthorization: typeof routes['transfers.verify_authorization']
    requestTransfer: typeof routes['transfers.request_transfer']
    getPendingTransfers: typeof routes['transfers.get_pending_transfers']
    approveTransfer: typeof routes['transfers.approve_transfer']
    rejectTransfer: typeof routes['transfers.reject_transfer']
  }
  inspections: {
    getAllSchools: typeof routes['inspections.get_all_schools']
    getSchoolById: typeof routes['inspections.get_school_by_id']
    approveSchool: typeof routes['inspections.approve_school']
    suspendSchool: typeof routes['inspections.suspend_school']
    generateSchoolCredentials: typeof routes['inspections.generate_school_credentials']
    sendGlobalCommunication: typeof routes['inspections.send_global_communication']
    sendSchoolCommunication: typeof routes['inspections.send_school_communication']
    getCommunicationHistory: typeof routes['inspections.get_communication_history']
    getGlobalStats: typeof routes['inspections.get_global_stats']
    getSchoolsStats: typeof routes['inspections.get_schools_stats']
    getPerformanceStats: typeof routes['inspections.get_performance_stats']
    generateSchoolsReport: typeof routes['inspections.generate_schools_report']
    generateTransfersReport: typeof routes['inspections.generate_transfers_report']
  }
  academics: {
    getClasses: typeof routes['academics.get_classes']
    createClass: typeof routes['academics.create_class']
    updateClass: typeof routes['academics.update_class']
    deleteClass: typeof routes['academics.delete_class']
    getClassStudents: typeof routes['academics.get_class_students']
    getSubjects: typeof routes['academics.get_subjects']
    addSubjectToClass: typeof routes['academics.add_subject_to_class']
  }
  pedagogicals: {
    getGrades: typeof routes['pedagogicals.get_grades']
    addGrade: typeof routes['pedagogicals.add_grade']
    updateGrade: typeof routes['pedagogicals.update_grade']
    publishGrades: typeof routes['pedagogicals.publish_grades']
    generateReportCard: typeof routes['pedagogicals.generate_report_card']
    getClassReportCards: typeof routes['pedagogicals.get_class_report_cards']
    getClassTimetable: typeof routes['pedagogicals.get_class_timetable']
    setTimetable: typeof routes['pedagogicals.set_timetable']
    getAcademicStats: typeof routes['pedagogicals.get_academic_stats']
    getStudentStats: typeof routes['pedagogicals.get_student_stats']
  }
  financials: {
    getFees: typeof routes['financials.get_fees']
    setFees: typeof routes['financials.set_fees']
    updateFees: typeof routes['financials.update_fees']
    deleteFees: typeof routes['financials.delete_fees']
    getPayments: typeof routes['financials.get_payments']
    recordPayment: typeof routes['financials.record_payment']
    getStudentPayments: typeof routes['financials.get_student_payments']
    generateReceipt: typeof routes['financials.generate_receipt']
    getIncomeReport: typeof routes['financials.get_income_report']
    getOutstandingPayments: typeof routes['financials.get_outstanding_payments']
    getStudentFinancialStatus: typeof routes['financials.get_student_financial_status']
    getFinancialStats: typeof routes['financials.get_financial_stats']
  }
  teachers: {
    getMyClasses: typeof routes['teachers.get_my_classes']
    getMySubjects: typeof routes['teachers.get_my_subjects']
    getAssignments: typeof routes['teachers.get_assignments']
    createAssignment: typeof routes['teachers.create_assignment']
    updateAssignment: typeof routes['teachers.update_assignment']
    deleteAssignment: typeof routes['teachers.delete_assignment']
    publishAssignment: typeof routes['teachers.publish_assignment']
    getSubmissions: typeof routes['teachers.get_submissions']
    gradeSubmission: typeof routes['teachers.grade_submission']
    getGrades: typeof routes['teachers.get_grades']
    addGrade: typeof routes['teachers.add_grade']
    updateGrade: typeof routes['teachers.update_grade']
    getForumTopics: typeof routes['teachers.get_forum_topics']
    createForumTopic: typeof routes['teachers.create_forum_topic']
    replyToTopic: typeof routes['teachers.reply_to_topic']
    pinTopic: typeof routes['teachers.pin_topic']
    lockTopic: typeof routes['teachers.lock_topic']
    getAttendance: typeof routes['teachers.get_attendance']
    markAttendance: typeof routes['teachers.mark_attendance']
  }
  parents: {
    getChildren: typeof routes['parents.get_children']
    getChildDetails: typeof routes['parents.get_child_details']
    getChildGrades: typeof routes['parents.get_child_grades']
    getChildReportCard: typeof routes['parents.get_child_report_card']
    getChildDiscipline: typeof routes['parents.get_child_discipline']
    getMessages: typeof routes['parents.get_messages']
    sendMessageToTeacher: typeof routes['parents.send_message_to_teacher']
    replyToMessage: typeof routes['parents.reply_to_message']
    getChildPayments: typeof routes['parents.get_child_payments']
    initiatePayment: typeof routes['parents.initiate_payment']
    getChildForumActivity: typeof routes['parents.get_child_forum_activity']
    justifyAbsence: typeof routes['parents.justify_absence']
  }
  students: {
    getMyProfile: typeof routes['students.get_my_profile']
    getMyGrades: typeof routes['students.get_my_grades']
    getMyReportCard: typeof routes['students.get_my_report_card']
    getMyDiscipline: typeof routes['students.get_my_discipline']
    getAssignments: typeof routes['students.get_assignments']
    getAssignmentDetail: typeof routes['students.get_assignment_detail']
    submitAssignment: typeof routes['students.submit_assignment']
    updateSubmission: typeof routes['students.update_submission']
    getMyForumQuestions: typeof routes['students.get_my_forum_questions']
    postForumQuestion: typeof routes['students.post_forum_question']
    replyToForum: typeof routes['students.reply_to_forum']
    getMessages: typeof routes['students.get_messages']
    sendMessageToTeacher: typeof routes['students.send_message_to_teacher']
    getMyTimetable: typeof routes['students.get_my_timetable']
    getMyAttendance: typeof routes['students.get_my_attendance']
  }
  disciplines: {
    getStudents: typeof routes['disciplines.get_students']
    getStudentDetails: typeof routes['disciplines.get_student_details']
    getAllIncidents: typeof routes['disciplines.get_all_incidents']
    reportIncident: typeof routes['disciplines.report_incident']
    updateIncident: typeof routes['disciplines.update_incident']
    deleteIncident: typeof routes['disciplines.delete_incident']
    getStudentIncidents: typeof routes['disciplines.get_student_incidents']
    applySanction: typeof routes['disciplines.apply_sanction']
    updateSanction: typeof routes['disciplines.update_sanction']
    getStudentDisciplineReport: typeof routes['disciplines.get_student_discipline_report']
    getClassDisciplineReport: typeof routes['disciplines.get_class_discipline_report']
    getDisciplineSummary: typeof routes['disciplines.get_discipline_summary']
    getDisciplineStats: typeof routes['disciplines.get_discipline_stats']
    notifyParent: typeof routes['disciplines.notify_parent']
  }
  messages: {
    getMessages: typeof routes['messages.get_messages']
    getUnreadCount: typeof routes['messages.get_unread_count']
    sendMessage: typeof routes['messages.send_message']
    markAsRead: typeof routes['messages.mark_as_read']
    deleteMessage: typeof routes['messages.delete_message']
    getConversations: typeof routes['messages.get_conversations']
    getConversation: typeof routes['messages.get_conversation']
    getNotifications: typeof routes['messages.get_notifications']
    markNotificationAsRead: typeof routes['messages.mark_notification_as_read']
    markAllAsRead: typeof routes['messages.mark_all_as_read']
    uploadAttachment: typeof routes['messages.upload_attachment']
  }
  interSchools: {
    searchSchools: typeof routes['inter_schools.search_schools']
    getSchoolPublicInfo: typeof routes['inter_schools.get_school_public_info']
    getExchanges: typeof routes['inter_schools.get_exchanges']
    startExchange: typeof routes['inter_schools.start_exchange']
    sendExchangeMessage: typeof routes['inter_schools.send_exchange_message']
    getBestPractices: typeof routes['inter_schools.get_best_practices']
    shareBestPractice: typeof routes['inter_schools.share_best_practice']
    getEvents: typeof routes['inter_schools.get_events']
    createEvent: typeof routes['inter_schools.create_event']
    joinEvent: typeof routes['inter_schools.join_event']
  }
  admins: {
    getUsers: typeof routes['admins.get_users']
    createUser: typeof routes['admins.create_user']
    updateUser: typeof routes['admins.update_user']
    deleteUser: typeof routes['admins.delete_user']
    activateUser: typeof routes['admins.activate_user']
    suspendUser: typeof routes['admins.suspend_user']
    getRoles: typeof routes['admins.get_roles']
    createRole: typeof routes['admins.create_role']
    updateRole: typeof routes['admins.update_role']
    getSystemLogs: typeof routes['admins.get_system_logs']
    getUserActivityLogs: typeof routes['admins.get_user_activity_logs']
  }
}
